@echo off
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
start explorer
echo ебать заскамил